# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Inc', 'IN CUSTODY'), ('FREE', 'N/A'), ('Par', 'PAROLED')], default='Inc', max_length=6),
        ),
    ]
