# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0002_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parole_date', models.DateTimeField(blank=True)),
                ('discharge_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='parole_date',
        ),
        migrations.AddField(
            model_name='member',
            name='typestate',
            field=models.CharField(blank=True, help_text='given name, last name first', max_length=10),
        ),
        migrations.AddField(
            model_name='release',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_member.Member'),
        ),
    ]
