# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0003_auto_20180207_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(blank=True, help_text="birthday in YYYYMMDD, if no full birthday, unknowns are '00'", max_length=10),
        ),
    ]
