# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0008_auto_20180215_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='change',
            new_name='verbose',
        ),
        migrations.AddField(
            model_name='change',
            name='attribute',
            field=models.CharField(blank=True, help_text='attribute changed', max_length=255),
        ),
    ]
