# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0009_auto_20180215_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='incarcerated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='parole_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
