# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0010_auto_20180215_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='typestate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
