# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0012_auto_20180514_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
