# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0013_auto_20180515_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Inc', 'IN CUSTODY'), ('FREE', 'N/A'), ('Par', 'PAROLED'), ('UNK', 'Unknown')], default='Inc', max_length=6),
        ),
    ]
