# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0014_auto_20180524_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='member',
            name='checked_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='so',
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
