# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0016_auto_20180705_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='life',
            field=models.NullBooleanField(),
        ),
    ]
