# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0017_member_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='life',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='msr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='so',
            field=models.BooleanField(default=False),
        ),
    ]
