# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0018_auto_20180705_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, help_text='first name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, help_text='last name', max_length=255, null=True),
        ),
    ]
