# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0019_auto_20180709_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='given_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='given_name_alpha',
        ),
    ]
