# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20180302_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='org_type',
            new_name='resource_type',
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
