# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20180524_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
