# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20180524_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
