# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_resource_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Resource Name'),
        ),
    ]
