# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20180524_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dedicated_to',
        ),
    ]
