# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0002_auto_20171202_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
